const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const base=path.join(__dirname,'..'),cache=new Map();let calls=0,payload;
const item={date:'2026-10-08',title:'Preparar campaña',workNotes:'Preparé la campaña durante media hora.',actualHours:.5,estimatedHours:null,progress:null,sourceQuote:'preparé la campaña'};
let reply={items:[item],warnings:[]},status=200,stop='end_turn';
const ctx=vm.createContext({console,Date,isNaN,isFinite,_get:(k,d)=>({PUBLISH_KEY:'test-only',ANTHROPIC_API_KEY:'mock-only'}[k]??d),CacheService:{getScriptCache:()=>({put:(k,v)=>cache.set(k,v)})},UrlFetchApp:{fetch:(url,opts)=>{calls++;payload=JSON.parse(opts.payload);assert.equal(url,'https://api.anthropic.com/v1/messages');return {getResponseCode:()=>status,getContentText:()=>JSON.stringify({stop_reason:stop,content:[{type:'text',text:JSON.stringify(reply)}]})};}}});
vm.runInContext(fs.readFileSync(path.join(base,'apps-script','VoiceAI.gs'),'utf8'),ctx);
ctx.body={requestId:'a'.repeat(32),publishKey:'wrong',text:'Hoy preparé la campaña durante media hora.',defaultDate:'2026-10-08',today:'2026-10-08',weekStart:'2026-10-05',salary:9000};
const run=s=>vm.runInContext(s,ctx);
assert.equal(run('_voiceRequest(body).authError'),true);assert.equal(calls,0);
ctx.body.publishKey='test-only';assert.equal(run('_voiceRequest(body).ok'),true);assert.equal(calls,1);
assert.equal(payload.model,'claude-sonnet-4-6');assert.equal(payload.output_config.format.type,'json_schema');
assert.equal(JSON.stringify(payload).includes('9000'),false);assert.equal(JSON.stringify(payload).includes('test-only'),false);
assert.equal(JSON.parse(cache.get('voice_'+ctx.body.requestId)).items[0].actualHours,.5);
assert.equal(run("_voiceDate('2026-02-30')"),false);
reply={items:[{...item,actualHours:25}],warnings:[]};assert.equal(run('_voiceRequest(body).ok'),false);
reply={items:[{...item,sourceQuote:'texto inventado'}],warnings:[]};assert.equal(run('_voiceRequest(body).ok'),false);
reply={items:[{...item,progress:101}],warnings:[]};assert.equal(run('_voiceRequest(body).ok'),false);
reply={items:[{...item,actualHours:null,progress:null}],warnings:[]};assert.equal(run('_voiceRequest(body).ok'),true);
status=401;assert.equal(run('_voiceRequest(body).ok'),false);status=200;stop='max_tokens';assert.equal(run('_voiceRequest(body).ok'),false);
ctx.body.today='invalid';const before=calls;assert.equal(run('_voiceRequest(body).ok'),false);assert.equal(calls,before);
new vm.Script(fs.readFileSync(path.join(base,'voice-ai.js'),'utf8'));
console.log('OK: autorización, transporte sin costes/claves, salida estructurada, fechas reales, citas verificadas, rangos, valores desconocidos y fallos de IA.');
